# Generated by Django 2.1.5 on 2019-02-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(default='image.png', upload_to='public/images'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(default='image.png'),
        ),
    ]
