# Generated by Django 2.1.5 on 2019-02-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_auto_20190208_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.TextField(default='', max_length=140),
        ),
    ]
