# Generated by Django 2.1.5 on 2019-02-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_auto_20190208_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_url',
            field=models.CharField(default='image.png', max_length=140),
        ),
    ]
